# -*- coding: utf-8 -*-
"""00_pytorch_fundamentals_video.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxMQTU0lzdcjnTvHVhRtZIzMimbBN-fR

## 00.pytorch.PyTorch Fundamentals

> Indented block



Resource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/

If a question https://github.com/mrdbourke/pytorch-deep-learning/discussions
"""

print("Hello Im excited to learn pytorch")

!nvidia-smi

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

"""## Intro to tensors

###creating tensors

PyTorch tensors are created using 'torch.Tensor()'-https://pytorch.org/docs/stable/tensors.html
"""

# scalar
scalar = torch.tensor(7)
scalar

scalar.ndim

#Get tensor back as Python int
scalar.item()

#vector
vector = torch.tensor([7,7])
vector

vector.ndim

vector.shape

# matrix
MATRIX = torch.tensor([[7,8],
             [9,10]])
MATRIX

MATRIX.ndim

# FIRST DIMENSION
MATRIX[0]

MATRIX[1]

MATRIX.shape

#TENSOR
TENSOR = torch.tensor([[[1,2,3],
            [3,4,5],
            [2,6,7]]])
TENSOR

TENSOR.ndim

# ONE 3BY3 TENSOR
# 第一个1 代表outer bracket，第二个数字3代表3个框住数字的框，第3个数字3代表一个最小框内的3个数字
TENSOR.shape

TENSOR[0]

TENSOR[1]

TENSOR[2]

"""#random tensors

Why random tensors?

Random tensors are important  because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

'Start with random numbers -> look at data -> update random numbers->look at data -> update random numbers'

Torch.random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html
"""

#Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

random_tensor.ndim

#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height,width, color channels (R, G, B)
random_image_size_tensor.shape,random_image_size_tensor.ndim
# torch.rand(3,4)=torch.rand(size=(3,4))

"""### Zeros and ones"""

#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

zeros*random_tensor

#create a tensor of all ones
ones = torch.ones(3,4)
ones

ones.dtype

random_tensor.dtype